In [ ]:
import pandas as pd
import torch

In [2]:
train_df = pd.read_csv("archive/train.csv")
test_df = pd.read_csv("archive/test.csv")
validation_df = pd.read_csv("archive/validation.csv")

In [3]:
train_df.head()
train_df.info()
train_df.isna().sum()
train_df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22593 entries, 0 to 22592
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          22593 non-null  int64
 1   NCBIGeneID          22593 non-null  int64
 2   Symbol              22593 non-null  object
 3   Description         22593 non-null  object
 4   GeneType            22593 non-null  object
 5   GeneGroupMethod     22593 non-null  object
 6   NucleotideSequence  22593 non-null  object
dtypes: int64(2), object(5)
memory usage: 1.2+ MB

Unnamed: 0            0
NCBIGeneID            0
Symbol                0
Description           0
GeneType              0
GeneGroupMethod       0
NucleotideSequence    0
dtype: int64

In [4]:
train_df.head()

,Unnamed: 0,NCBIGeneID,Symbol,Description,GeneType,GeneGroupMethod,NucleotideSequence
0,0,106481178,RNU4-21P,"RNA, U4 small nuclear 21, pseudogene",PSEUDO,NCBI Ortholog,<AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAG...
1,1,123477792,LOC123477792,Sharpr-MPRA regulatory region 12926,BIOLOGICAL_REGION,NCBI Ortholog,<CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCG...
2,2,113174975,LOC113174975,Sharpr-MPRA regulatory region 7591,BIOLOGICAL_REGION,NCBI Ortholog,<TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTC...
3,3,116216107,LOC116216107,CRISPRi-validated cis-regulatory element chr10...,BIOLOGICAL_REGION,NCBI Ortholog,<CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGC...
4,4,28502,IGHD2-21,immunoglobulin heavy diversity 2-21,OTHER,NCBI Ortholog,<AGCATATTGTGGTGGTGACTGCTATTCC>

In [5]:
train_df.columns

Index(['Unnamed: 0', 'NCBIGeneID', 'Symbol', 'Description', 'GeneType',
       'GeneGroupMethod', 'NucleotideSequence'],
      dtype='object')

In [6]:
train_df = train_df[["Description","NucleotideSequence"]]

In [7]:
train_df["prefix"] = train_df["Description"].str.extract(r'^([A-Za-z]+)')

In [46]:
train_df["Description"] = train_df["Description"].str.replace(r"[,]", "", regex=True)
train_df["NucleotideSequence"] = train_df["NucleotideSequence"].str.replace(r"[<>]", "", regex=True)

In [49]:
train_df["words_size"] = train_df["Description"].str.split().apply(lambda words: [len(w) for w in words])

In [47]:
train_df.columns

Index(['Description', 'NucleotideSequence', 'prefix'], dtype='object')

In [11]:
X_train =  train_df["Description"]
y_train  = train_df["NucleotideSequence"]

X_test = test_df["Description"]
y_test = test_df["NucleotideSequence"]

In [48]:
train_df.head(10)

,Description,NucleotideSequence,prefix
0,RNA U4 small nuclear 21 pseudogene,AGCTTAGCACAGTGGCAGTATCATAGGCAGTGAGGTTTATCCGAGG...,RNA
1,Sharpr-MPRA regulatory region 12926,CTGGAGCGGCCACGATGTGAACTGTCACCGGCCACTGCTGCTCCGA...,Sharpr
2,Sharpr-MPRA regulatory region 7591,TTCCCAATTTTTCCTCTGCTTTTTAATTTTCTAGTTTCCTTTTTCC...,Sharpr
3,CRISPRi-validated cis-regulatory element chr10...,CGCCCAGGCTGGAGTGCAGTGGCGCCATCTCGGCTCACTGCAGGCT...,CRISPRi
4,immunoglobulin heavy diversity 2-21,AGCATATTGTGGTGGTGACTGCTATTCC,immunoglobulin
5,U7 small nuclear RNA,AAGTGTTACAGCTCTTTTAGAATTTGTCTAGCAGGTTTTCCTACTA...,U
6,small nucleolar RNA SNORA27,CACTCCCCTTTCATTTTACCATTGAGGCTTATGTCTTTATTGGTTG...,small
7,H2A clustered histone 4,GTAGTTTCATTACATTTTCTTGTGGCGATTTTCCCTTATCAGAAGT...,H
8,microRNA 3619,ACGGCATCTTTGCACTCAGCAGGCAGGCTGGTGCAGCCCGTGGTGG...,microRNA
9,small nucleolar RNA U13,ATCCTTTTGTAGTTCATGAGCGTGATGATTGGGTGTTCACATGCAT...,small

In [45]:
all_words = train_df["Description"]
unique_words = all_words.nunique()
unique_words

21033